import Head from "next/head";
import css from "@/styles/Home.module.css";
import { useState } from "react";
import { bubbleSort } from "@/utils/bubblesort";
import { bucketSort } from "@/utils/bucketSort";
import { countingSort } from "@/utils/countingsort";
import { insertionSort } from "@/utils/insertiondort";
import { selectionSort } from "@/utils/selectionsort";
import { quickSort } from "@/quicksort";

export default function Home() {
  function generateRandomNumbers() {
    return [...Array(quantity)].map((_) => Math.ceil(Math.random() * quantity));
  }

  const [isSorting, setIsSorting] = useState(false);
  const [quantity, setQuantity] = useState(40);
  const [numbers, setNumbers] = useState(generateRandomNumbers);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={css.display}>
          {numbers.map((number, index) => {
            return (
              <div
                key={index}
                className={css.number}
                style={{
                  width: `${(1 / quantity) * 80}%`,
                  height: `${(number / quantity) * 300 + 20}px`,
                  background: `linear-gradient(to top right, hsl(${
                    (number * 360) / Math.max(...numbers)
                  }, 60%, 50%), hsl(${(number * 320) / Math.max(...numbers)}, 40%, 50%))`,
                }}
              >
                {number}
              </div>
            );
          })}
        </div>
        <div className={css.buttons}>
          <button disabled={isSorting} onClick={() => setNumbers(generateRandomNumbers)}>
            Generate random numbers
          </button>
          <button disabled={isSorting} onClick={() => bubbleSort(numbers, setNumbers, setIsSorting)}>
            Bubble sort
          </button>
          <button disabled={isSorting} onClick={() => bucketSort(numbers, setNumbers, setIsSorting)}>
            Bucket sort
          </button>
          <button disabled={isSorting} onClick={() => countingSort(numbers, setNumbers, setIsSorting)}>
            Counting sort
          </button>
          <button disabled={isSorting} onClick={() => insertionSort(numbers, setNumbers, setIsSorting)}>
            Insertion sort
          </button>
          {/* <button disabled={isSorting}>Merge sort</button> */}
          {/* <button disabled={isSorting} onClick={() => quickSort(numbers, setNumbers, setIsSorting)}>
            Quick sort
          </button> */}
          <button disabled={isSorting} onClick={() => selectionSort(numbers, setNumbers, setIsSorting)}>
            Selection sort
          </button>
        </div>
      </main>
    </>
  );
}
